export enum ActionTypeStates {
  INPROGRESS = "_INPROGRESS",
  SUCCESS = "_SUCCESS",
  FAIL = "_FAIL"
}

enum ActionTypeKeys {
  GET_GROUPS_INPROGRESS = "GET_GROUPS_INPROGRESS",
  GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS",
  GET_GROUPS_FAIL = "GET_GROUPS_FAIL",
  GET_SITES_INPROGRESS = "GET_SITES_INPROGRESS",
  GET_SITES_SUCCESS = "GET_SITES_SUCCESS",
  GET_SITES_FAIL = "GET_SITES_FAIL",
  UPDATE_SITE_INPROGRESS = "UPDATE_SITE_INPROGRESS",
  UPDATE_SITE_SUCCESS = "UPDATE_SITE_SUCCESS",
  UPDATE_SITE_FAIL = "UPDATE_SITE_FAIL",
  DELETE_SITE_INPROGRESS = "DELETE_SITE_INPROGRESS",
  DELETE_SITE_SUCCESS = "DELETE_SITE_SUCCESS",
  DELETE_SITE_FAIL = "DELETE_SITE_FAIL",
  ADD_SITE_INPROGRESS = "ADD_SITE_INPROGRESS",
  ADD_SITE_SUCCESS = "ADD_SITE_SUCCESS",
  ADD_SITE_FAIL = "ADD_SITE_FAIL",
  SIGN_IN = "SIGN_IN",
  SIGN_OUT = "SIGN_OUT",
  UPDATE_GROUP_INPROGRESS = "UPDATE_GROUP_INPROGRESS",
  UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS",
  UPDATE_GROUP_FAIL = "UPDATE_GROUP_FAIL",
  ADD_GROUP_INPROGRESS = "ADD_GROUP_INPROGRESS",
  ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS",
  ADD_GROUP_FAIL = "ADD_GROUP_FAIL",
  DELETE_GROUP_INPROGRESS = "DELETE_GROUP_INPROGRESS",
  DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS",
  DELETE_GROUP_FAIL = "DELETE_GROUP_FAIL"
}

export default ActionTypeKeys;
