export enum ActionTypeStates {
  INPROGRESS = "_INPROGRESS",
  SUCCESS = "_SUCCESS",
  FAIL = "_FAIL"
}

enum ActionTypeKeys {
  GET_GROUPS_INPROGRESS = "GET_GROUPS_INPROGRESS",
  GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS",
  GET_GROUPS_FAIL = "GET_GROUPS_FAIL",
  GET_SITES_INPROGRESS = "GET_SITES_INPROGRESS",
  GET_SITES_SUCCESS = "GET_SITES_SUCCESS",
  GET_SITES_FAIL = "GET_SITES_FAIL",
  UPDATE_SITE_INPROGRESS = "UPDATE_SITE_INPROGRESS",
  UPDATE_SITE_SUCCESS = "UPDATE_SITE_SUCCESS",
  UPDATE_SITE_FAIL = "UPDATE_SITE_FAIL",
  SIGN_IN = "SIGN_IN",
  SIGN_OUT = "SIGN_OUT"
}

export default ActionTypeKeys;
